### ISSUE TITLE
useLittera can't be used in an object

### ISSUE THREAD

**Issue by xomod** [DRFR0ST/react-littera#8]
**Is your feature request related to a problem? Please describe.**
I wanted to use useLittera in my object, but unfortunately it's impossible. useLittera can only be used in a component, which is very sad for me.

**Comment by DRFR0ST** [comment]
You can use `translate` method to get translated object returned but you have to pass a locale which is stored in Reacts context. You probably won't be able to read the context state outside of render functions/classes. 
As a walk around you could wrap your objects with a hook and then get it returned like in a regular scenario.

It will probably not solve your problem but you might do it like in the example below:

```typescript
const useMyObjects = () => {
    const translated = useLittera(translations);
    
    return [
      {
         title: `Category: ${translated.cat01Title}`,
         isCool: true,
         followers: 69
      },
      {
         title: `Category: ${translated.cat02Title}`,
         isCool: true,
         followers: 420
      }
    ]
}

const YourComponent = () => {
     const myObjects = useMyObjects();

     return <h1>{myObjects[0].title}</h1>
}
```

**Comment by xomod** [comment]
Thanks my master, that's working!
